server.:
  port: 5000
backenddevtest:
  rest:
    client:
      product:
        base-url: http://localhost:3001
        connection-timeout: 5000
        read-timeout: 5000
logging:
  level:
    root: INFO